# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4v8EUsWtm02DDz-u4yAcRVzoVlkISQB
"""

def maximum3(a,b,c):
   max=a
   if b>max:
     max=b
   if c>max:
     max=c
   return max