# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4v8EUsWtm02DDz-u4yAcRVzoVlkISQB
"""

class B:
    def setvar(self,a,b):
        self.x=a
        c=a*b
        self.y=c