# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4v8EUsWtm02DDz-u4yAcRVzoVlkISQB
"""

class person:
    def __init__(self,s,n):
     self.score=s
     self.name=n
     print("hello")
h=person (56,"hasan")