# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4v8EUsWtm02DDz-u4yAcRVzoVlkISQB
"""

def Mean ():
    counter = 0
    sum = 0
    while i != 1000:
      i=int(input())
      sum += 1
      counter += 1
    return (sum-1000)/(counter-1)