# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4v8EUsWtm02DDz-u4yAcRVzoVlkISQB
"""

class A ():
    name="ali"
    age=25

A.name="reza"
print (A.name)

test=A()
test.name="ahmad"
print(test.age)