# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4v8EUsWtm02DDz-u4yAcRVzoVlkISQB
"""

l.sort()
  count_min=l.count(l[0])
  count_max=l.count(l[-1])
  return l[-1],count_max,l[0],count_min