# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4v8EUsWtm02DDz-u4yAcRVzoVlkISQB
"""

class students:
    def init(self,id,name):
        self.id=id
        self.name=name
    def del__(self):
        print(self.name,"Deleted")
    def mean(self):
        input ()


        return sum/vs
    def is_mashroot(self):
        if self.mean()<12:
            return True
        else:
            return ("false")
    def str(self):
        print('this class is student')