# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4v8EUsWtm02DDz-u4yAcRVzoVlkISQB
"""

def fanc1():
   print()
print('salam')
fanc1()
fanc1()
print('khodafezz')