# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4v8EUsWtm02DDz-u4yAcRVzoVlkISQB
"""

def b_sort (k=[],s=10):
 if k is not none:
   for i in range (s-1):
    for j in range (s-1-i):
      if k[j]>k[j+1]:
         temp =k[j]
         k[j]=k[j+1]
         k[j+1]=temp
         return 1
   else:
         return 0