# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_YEubSWA9axJ2fHjvjuUZO8Z_VTBj_u9
"""

def fanc1():
   print()
print('salam')
fanc1()
fanc1()
print('khodafezz')