# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4v8EUsWtm02DDz-u4yAcRVzoVlkISQB
"""

l=[]
  k=0
  while 2>1:
    k=int(input())
    if k==5:
       break
    l.append(k)
  "return"l