# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4v8EUsWtm02DDz-u4yAcRVzoVlkISQB
"""

def maximum100():
   a=input()
   a=int(a)
   max=a
   for i in range(99):
      a=int(input())
      if a>max:
         max=a
         return max